### ISSUE TITLE
Cannot be activated

### ISSUE THREAD

**Issue by Golgovskiy** [williamchange/b3dsdf#1]
bpy.utils.register_class(NODE_OT_group_add)
RuntimeError: Error: Registering operator class: 'NODE_OT_group_add', invalid bl_idname '2dsdf.b3dsdf-master', at position 12

**Comment by williamchange** [comment]
@Golgovskiy this happens when you download directly from the repository. If you download the zip file from the release page it will enable without issues.

**Comment by williamchange** [comment]
this should now work when installing from the repo zip file directly
