### ISSUE TITLE
Nodes are not available for Geometry Nodes

### ISSUE THREAD

**Issue by benthillerkus** [williamchange/b3dsdf#2]
Yesterday, Blender [merged a patch](https://developer.blender.org/rB838c4a97f1d6b993f4c866c474eb02d929f0ca1d) that [allows meshing SDFs](https://twitter.com/lateasusual_/status/1537794753722556417) in Geometry nodes.

So it would be nice to be able to add the nodes from the Geo nodes editor directly

**Comment by williamchange** [comment]
https://twitter.com/cmzw_/status/1538146026296836096

Right now I don't plan to implement geometry nodes variants(focusing on shader nodes for now) but they can be converted to geometry nodes via an add-on mentioned in this twitter thread.
