### ISSUE TITLE
Submit the node resource file for this plugin as an asset to the official asset repository

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [williamchange/b3dsdf#4]
Just as [this](https://wiki.blender.org/wiki/Reference/Release_Notes/Blender_Asset_Bundle)

So we need add some preview image for this node file
For example：
![image](https://user-images.githubusercontent.com/65578116/221387533-348cbe58-52ce-4db4-adec-785d0d7ea7bb.png)

![image](https://user-images.githubusercontent.com/65578116/221387545-373f341e-a482-4b4b-88a8-9293c749ce4c.png)

![image](https://user-images.githubusercontent.com/65578116/221387552-1aa098d7-78c5-4377-bce4-8d489fcb1216.png)

**Comment by williamchange** [comment]
Thanks for telling me this, I don't plan to submit right now but I will keep this open for the time being.

**Comment by williamchange** [comment]
No plans to submit but I might release an asset pack like this later.
