### ISSUE TITLE
doesnt work in blender 4.x 

### ISSUE THREAD

**Issue by Ulf3000** [williamchange/b3dsdf#6]
Hi thanx for this outstanding work ! but is there a quick fix to make this work in blender 4+ ? im heavily relying on the new realtime compositor now and theres no going back for my main project. the sdf menu doesnt show up in the add menu in shader editor in any blender version higer than 3.3

(second question : was this inspired by gooengine(blender custom build) sdf nodes ? they have a similar set of nodes. )

**Comment by Ulf3000** [comment]
im just dumb , workspace addon filtering was turned on somehow (i saved that accidentily with my startup file) and i never ever looked at that feature again afterwards. so all my saved files wouldnt show the menu but new files did(after i deleted my custom startup file). took me hours to find out 🤢.   it works fine in 4.1 ! no problems !

**Comment by williamchange** [comment]
To answer your second question, if I recall correctly some of gooengine's SDF shader nodes are actually based on the [D6464 blender patch](https://archive.blender.org/developer/D6464).

I mostly started this pack as a personal library based on [Inigo Quilez's 2d distance functions](https://iquilezles.org/articles/distfunctions2d/) but over time I extended it to include more shapes from [these references](https://github.com/williamchange/b3dsdf#references) (and the D6464 patch)
