### ISSUE TITLE
Have a plan to upload it to official addon store？

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [williamchange/b3dsdf#7]
Addon system of 4.2+ has big change.
We have official addon store now.

It's a good idea!
[Let's go!](https://extensions.blender.org/add-ons/)

**Comment by williamchange** [comment]
The add-on store is experimental right now so it's subject to change.

![image](https://github.com/williamchange/b3dsdf/assets/830253/18896958-0a14-49f0-a366-fb1fc3e581be)

**Comment by BUGProtectionAssociation** [comment]
> The add-on store is experimental right now so it's subject to change.附加商店目前处于实验阶段，因此可能会发生变化。
> 

Well I think that is time try to update it to official website now (If you have time...)
